config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'quizzes#index'
  resources :quizzes, only: [:index, :post, :new, :create, :show] do
    collection do
      get 'inde'
      get 'keshimas'
      get 'judge'
      get 'search'
      post 'modal'
      get 'category_children', defaults: {format:'json'}
    end
    member do
      post 'create_judge'
      post 'update_judge'
      delete 'destroy_judge'
      get 'find_by_parent'
      get 'find_by_children'
    end
    resources :favorites, only: [:create, :destroy]
    resources :mistakes,  only: [:create, :destroy]
  end
  resources :users, only: [:show] do
    collection do
      get 'category_children', defaults: {format:'json'}
    end
    member do
      get 'favorite'
      get 'mistake'
    end
  end
  resources :choices, only: [:index, :post, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :quizzes
  has_ancestry
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :quiz
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
end

app/models/judge.rb
class Judge < ApplicationRecord
  validates :quiz_id, presence: true, uniqueness: { scope: :user_id }
  validates :user_id, presence: true, uniqueness: { scope: :quiz_id }
  belongs_to :quiz
  belongs_to :user
end

app/models/mistake.rb
class Mistake < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
end

app/models/modalimage.rb
class Modalimage < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many   :choices, dependent: :destroy
  belongs_to :category
  has_many   :users, through: :favorite
  has_many   :favorites
  has_many   :mistakes
  has_many   :judges
  has_many   :users, through: :judges

  accepts_nested_attributes_for :choices
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :quizzes, through: :favorites
  has_many :favorites
  has_many :mistakes
  has_many :judges
  has_many :quizzes, through: :judges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @quiz = Quiz.find(params[:quiz_id])
    if Favorite.create(user_id: current_user.id, quiz_id: @quiz.id)
    else
    end
  end
  
  def destroy
    @quiz = Quiz.find(params[:quiz_id])
    if favorite = Favorite.find_by(user_id: current_user.id, quiz_id: @quiz.id)
      favorite.delete
    else
    end
  end

end

app/controllers/mistakes_controller.rb
class MistakesController < ApplicationController

  def create
    @quiz = Quiz.find(params[:quiz_id])
    if Mistake.create(user_id: current_user.id, quiz_id: @quiz.id)
    else
    end
  end
  
  def destroy
    @quiz = Quiz.find(params[:quiz_id])
    if mistake = Mistake.find_by(user_id: current_user.id, quiz_id: @quiz.id)
      mistake.delete
    else
    end
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:create_judge, :update_judge, :destroy_judge]
  before_action :set_judge, only: [:update_judge, :destroy_judge]
  def index
    @categories = Category.where(ancestry: nil).limit(13)
    @quizzes = Quiz.order("RAND()").where(status: 1..Float::INFINITY).limit(10)
  end

  def keshimas
    @images = Modalimage.order("RAND()").limit(9)
  end

  def new
    @quiz = Quiz.new
    4.times{@quiz.choices.build}
  end
  
  def create
    @quiz = Quiz.new(quiz_params)
    if @quiz.save
      redirect_to new_quiz_path, notice: '完了'
    else
      render :new
    end
  end

  def show
    @quizzes = Quiz.where(category_id: params[:id]).order("RAND()").limit(10)
  end

  def modal
    Modalimage.create(modal_params)
  end

  def search
    @quizzes = Quiz.where('quiz LIKE(?)', "%#{params[:keyword]}%")
    .or(Quiz.where('explanation LIKE(?)', "%#{params[:keyword]}%")).limit(20)
  end

  def find_by_parent
    @quizzes = []
    Category.find(params[:id]).children.each do |child|
      child.quizzes.order("RAND()").each do |quiz|
        @quizzes << quiz
      end
    end
  end

  def find_by_children
    @quizzes = Quiz.where(category_id: params[:id])
  end
  
  # judge関係////////////////////////////////////////////
  def judge
    @quizzes = Quiz.where.not(user_id: current_user.id).order("RAND()").limit(10)
  end

  def create_judge
    Judge.create(judge_params)
    @quiz.increment!(:status, params['format'].to_i)
  end
  
  def update_judge
    @judge.increment!(:judge, params['format'].to_i)
    @quiz.increment!(:status, params['format'].to_i)
  end
  
  def destroy_judge
    @judge.destroy
    @quiz.increment!(:status, params['format'].to_i)
  end
  # judge関係////////////////////////////////////////////




  # 非同期通信/////////////////////
  def category_children
    @children = Category.find(params[:category]).children
  end


  private
  def quiz_params
    params.require(:quiz).permit(:quiz, :answer, :image, :explanation, :category_id, choices_attributes:[:id, :text, :correct]).merge(user_id: current_user.id)
  end

  def modal_params
    params.permit(:image)
  end

  def judge_params
    params.permit(:judge).merge(user_id: current_user.id, quiz_id: @quiz.id, judge: params['format'].to_i)
  end

  def set_quiz
    @quiz = Quiz.find(params[:id])
  end

  def set_judge
    @judge = Judge.find_by(user_id: current_user.id, quiz_id: @quiz.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @parents = Category.where(ancestry: nil)
  end

  def category_children
    @children = Category.find(params[:category]).children
  end

  def favorite
    @favorites = Favorite.where(user_id: current_user.id)
    @quizzes = []
    @favorites.each do |fav|
      @quizzes << fav.quiz
    end
  end
  
  def mistake
    @mistakes = Mistake.where(user_id: current_user.id)
    @quizzes = []
    @mistakes.each do |mis|
      @quizzes << mis.quiz
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
.header
  .header__left
    = link_to 'マイページ', user_path(current_user.id)
  .header-spacer
  .header__center
    = link_to 'top', root_path
  .header__search
    %input{id: 'search', name: 'keyword', placeholder: 'クイズを検索する'}
    = fa_icon('search')
  .header__right
    = link_to 'クイズを投稿する', new_quiz_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QuizApp
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

  %body
    - if user_signed_in?
      = render './layouts/header'
    .container
      = yield

app/views/quizzes/find_by_children.html.haml
= render './templates/quizzes'

app/views/quizzes/find_by_parent.html.haml
= render './templates/quizzes'

app/views/quizzes/index.html.haml
= render './templates/quizzes'

app/views/quizzes/judge.html.haml
.quiz-container
  - if @quizzes
    - @quizzes.each_with_index do |quiz, i|
      .quiz-content.quiz-bg{'data-quiz_id': "#{quiz.id}"}
        .quiz-title
          Q.
          = i + 1
        .quiz-quiz
          = quiz.quiz
        .quiz-image
          = quiz.image
        .explanation.hidden
          .explanationch.hiddench
            正解！
          .explanationih.hiddenih
            残念！
          .explanationp
            = quiz.explanation
        .answer.hidden
          正解は↓
        .choices      
          - quiz.choices.shuffle.each do |c|
            - if c.correct == 0
              .judge-ichoice.ichoice{"data-id": "#{c.correct}"} 
                .choice
                  = "#{c.text}" 
            - else
              .cchoice{"data-id": "#{c.correct}"}
                .choice
                  = "#{c.text}" 
        .judge
          .judge-title
            %h2 評価する
          .judge-button
            - if !Judge.exists?(user_id: current_user.id, quiz_id: quiz.id)
              .judge-good
                = link_to create_judge_quiz_path(quiz, 1), method: :post, class: 'judge-yet goodbtn' do
                  = fa_icon('thumbs-up')
              .judge-bad
                = link_to create_judge_quiz_path(quiz, -1), method: :post, class: 'judge-yet badbtn' do
                  = fa_icon('thumbs-down')
            - elsif Judge.exists?(user_id: current_user.id, quiz_id: quiz.id, judge: 1)
              .judge-good
                = link_to destroy_judge_quiz_path(quiz, -1), method: :delete, class: 'judged-good goodbtn' do
                  = fa_icon('thumbs-up')
              .judge-bad
                = link_to update_judge_quiz_path(quiz, -2), method: :post, class: 'judge-yet badbtn' do
                  = fa_icon('thumbs-down')
            - elsif Judge.exists?(user_id: current_user.id, quiz_id: quiz.id, judge: -1)
              .judge-good
                = link_to update_judge_quiz_path(quiz, 2), method: :post, class: 'judge-yet goodbtn' do
                  = fa_icon('thumbs-up')
              .judge-bad
                = link_to destroy_judge_quiz_path(quiz, 1), method: :delete, class: 'judged-bad badbtn' do
                  = fa_icon('thumbs-down')

.footer
  = link_to "次の10問", redirect_to: :back, class: "next"

app/views/quizzes/keshimas.html.haml
.open 
  ＋詳しく見る
.modal
  .modal__head
    この中で人名由来で名前がついたものを選択してください
  .modal__inner
    - @images.shuffle.each_with_index do |image, i|
      .image-box
        .image{style: "background-image: url(#{image.image})", 'data-id' => "#{image.correct}", id: "#{i}"}
  .not-robot 
    %h2 私はロボットではありません
.clear.hidden
  クリア
.keshimas
  .keshimas__row
    .keshimas__row--box
      %p.keshimas-block 秋
    .keshimas__row--box
      %p.keshimas-block 意
    .keshimas__row--box
      %p.keshimas-block 心
    .keshimas__row--box
      %p.keshimas-block 地
  .keshimas__row
    .keshimas__row--box
      %p.keshimas-block 鮑
    .keshimas__row--box
      %p.keshimas-block 刀
    .keshimas__row--box
      %p.keshimas-block 気
    .keshimas__row--box
      %p.keshimas-block 質
  .keshimas__row
    .keshimas__row--box
      %p.keshimas-block 魚
    .keshimas__row--box
      %p.keshimas-block 煙
    .keshimas__row--box
      %p.keshimas-block 地
    .keshimas__row--box
      %p.keshimas-block 面
  .keshimas__row
    .keshimas__row--box
      %p.keshimas-block 草
    .keshimas__row--box
      %p.keshimas-block 乙
    .keshimas__row--box
      %p.keshimas-block 女
    .keshimas__row--box
      %p.keshimas-block 子
.button-area
  %button
    正解！

= form_with url: modal_quizzes_path do |f|
  = f.file_field :image
  = f.submit

app/views/quizzes/new.html.haml
.quiz-new-bg
  .quiz-new
    = form_for @quiz do |f|
      .quiz-new__form
        %h2
          問題を入力してください
        = f.text_field :quiz, placeholder: "問題文を入力してください"
        = f.text_field :image, placeholder: "image"
        = f.text_field :explanation, placeholder: "解説を入力して下さい"
        .category-parent
          = f.select :category, Category.where(ancestry: nil).map{|x| [x.name, x.id]}, prompt: "---"
        .category-children
      .choices-form
        - i = 1
        = f.fields_for :choices do |fc|
          .choice-form
            %p 
              = "選択肢#{i}"
            = fc.text_field :text, placeholder: "選択肢#{i}"
            = fc.text_field :correct, placeholder: "正解なら1不正解は0"
            - i += 1
      = f.submit "クイズを投稿する", id: 'quiz-new__submit'

app/views/quizzes/show.html.haml
.container
  .quiz-container
    - @quizzes.each_with_index do |quiz, i|
      .quiz-content.quiz-bg
        .quiz-title
          Q
          = i + 1
        .quiz-quiz
          = quiz.quiz
        .quiz-image
          = quiz.image
        
        .explanation.hidden
          .explanationch.hiddench
            正解！
          .explanationih.hiddenih
            残念！
          .explanationp
            = quiz.explanation
        .answer.hidden
          正解は↓
        .choices      
          - quiz.choices.shuffle.each do |c|
            - if !Mistake.exists?(user_id: current_user.id, quiz_id: quiz.id) && c.correct == 0
              .ichoice{"data-id": "#{c.correct}"} 
                = link_to "#{c.text}", quiz_mistakes_path(quiz), method: :post, class: "addmistake choice" 
            - elsif c.correct == 0
              .ichoice{"data-id": "#{c.correct}"} 
                .choice
                  = "#{c.text}" 
            - else
              .cchoice{"data-id": "#{c.correct}"}
                .choice
                  = "#{c.text}" 
        .add-favorite.btn{"data-id": "#{quiz.id}"}
          - if !Favorite.exists?(user_id: current_user.id, quiz_id: quiz.id)
            = link_to "お気に入りに追加", quiz_favorites_path(quiz), method: :post, class:"addfavorite"
          - else
            = link_to "お気に入り解除", quiz_favorite_path(quiz), method: :delete, class: "removefavorite"
.footer
  = link_to "次の10問", redirect_to: :back, class: "next"

app/views/templates/_quizzes.html.haml
.container
  .quiz-container
    - if @quizzes
      - @quizzes.each_with_index do |quiz, i|
        .quiz-content.quiz-bg
          .quiz-title
            Q.
            = i + 1
          .quiz-quiz
            = quiz.quiz
          .quiz-image
            = quiz.image
          
          .explanation.hidden
            .explanationch.hiddench
              正解！
            .explanationih.hiddenih
              残念！
            .explanationp
              = quiz.explanation
          .answer.hidden
            正解は↓
          .choices      
            - quiz.choices.shuffle.each do |c|
              - if !Mistake.exists?(user_id: current_user.id, quiz_id: quiz.id) && c.correct == 0
                .ichoice{"data-id": "#{c.correct}"} 
                  = link_to "#{c.text}", quiz_mistakes_path(quiz), method: :post, class: "addmistake choice" 
              - elsif c.correct == 0
                .ichoice{"data-id": "#{c.correct}"} 
                  .choice
                    = "#{c.text}" 
              - else
                .cchoice{"data-id": "#{c.correct}"}
                  .choice
                    = "#{c.text}" 
          .add-favorite.btn{"data-id": "#{quiz.id}"}
            - if !Favorite.exists?(user_id: current_user.id, quiz_id: quiz.id)
              = link_to "お気に入りに追加", quiz_favorites_path(quiz, current_user.id), method: :post, class:"addfavorite"
            - else
              = link_to "お気に入り解除", quiz_favorite_path(quiz, current_user.id), method: :delete, class: "removefavorite"
          - if request.url.include?('mistake')
            .remove-mistake.btn{"data-id": "#{quiz.id}"}
              = link_to "覚えた！", quiz_mistake_path(quiz, current_user.id), method: :delete, class:"removemistake"
.footer
  = link_to "次の10問", redirect_to: :back, class: "next"       

app/views/users/favorite.html.haml
= render './templates/quizzes'

app/views/users/mistake.html.haml
= render './templates/quizzes'

app/views/users/show.html.haml
.mypage-container
  .to-categories
    カテゴリーから検索
    %select#selectparent
      %option{value: ""}
        = "---"
      - @parents.each do |parent|
        %option{value: parent.id}
          = parent.name
    #selectchildren
    %h2.search-by-category 検索する
  .to-favorites
    = link_to favorite_user_path do
      お気に入り問題
      %p 問題を解く
  .to-mistakes
    = link_to mistake_user_path do
      ミスった問題
      %p 問題を解く
  .to-keshimas
    = link_to keshimas_quizzes_path do
      漢字ケシマス
  .to-judge
    = link_to judge_quizzes_path do
      問題を評価する
= link_to 'ログアウト', destroy_user_session_path, method: :delete
%br
%br